---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 1
  rounds:
  - label: query
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    arguments:
      assets: 10
    callback: benchmarks/scenario/mzero/querymproof.js
  - label: ShareInitiation
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 30
    arguments:
      assets: 10
    callback: benchmarks/scenario/mzero/shareinit.js
  - label: ShareUpdate
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 30
    arguments:
      assets: 10
    callback: benchmarks/scenario/mzero/shareupdate.js
  - label: ShareRevocation
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 30
    arguments:
      assets: 10
    callback: benchmarks/scenario/mzero/sharerev.js
  - label: ShareDissemination
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 30
    arguments:
      assets: 10
    callback: benchmarks/scenario/mzero/sharedis.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
