---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 20
  rounds:
  - label: ShareInitiation
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 3000
    rateControl:
    - type: fixed-feedback-rate
      opts:
        tps: 1200
    arguments:
      assets: 10
    callback: benchmarks/scenario/mzero/shareinit.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
